// US/California curriculum subjects for catutors.com
export const ALL_SUBJECTS = [
  // Core academics
  "Mathematics",
  "Algebra",
  "Geometry",
  "Trigonometry",
  "Pre-Calculus",
  "Calculus",
  "Statistics",
  "English",
  "Reading & Writing",
  "Essay Writing",
  "Creative Writing",
  "Literature",
  "Science",
  "Biology",
  "Chemistry",
  "Physics",
  "Earth Science",
  "Environmental Science",
  "History",
  "US History",
  "World History",
  "Government & Civics",
  "Economics",
  "Geography",
  // AP Courses
  "AP Calculus AB",
  "AP Calculus BC",
  "AP Statistics",
  "AP Physics 1",
  "AP Physics 2",
  "AP Physics C",
  "AP Chemistry",
  "AP Biology",
  "AP Environmental Science",
  "AP English Language",
  "AP English Literature",
  "AP US History",
  "AP World History",
  "AP Government",
  "AP Economics (Macro)",
  "AP Economics (Micro)",
  "AP Psychology",
  "AP Computer Science A",
  "AP Computer Science Principles",
  "AP Spanish",
  "AP French",
  // Test Prep
  "SAT Prep",
  "ACT Prep",
  "SAT Math",
  "SAT Reading & Writing",
  "PSAT Prep",
  "GRE Prep",
  "GMAT Prep",
  "LSAT Prep",
  "MCAT Prep",
  // Languages
  "Spanish",
  "French",
  "Mandarin Chinese",
  "Japanese",
  "German",
  "Italian",
  "Korean",
  "Arabic",
  "American Sign Language",
  // Computer Science & Tech
  "Computer Science",
  "Python",
  "Java",
  "JavaScript",
  "Web Development",
  "Data Science",
  "Coding for Kids",
  // Arts & Music
  "Music Theory",
  "Piano",
  "Guitar",
  "Violin",
  "Art",
  "Drawing & Painting",
  "Photography",
  // Elementary
  "Elementary Math",
  "Elementary Reading",
  "Phonics",
  "Handwriting",
  "Elementary Science",
  // Other
  "Accounting",
  "Finance",
  "Special Education",
  "Study Skills",
  "Homework Help",
].sort();
